(() => {
  'use strict';
  const TYPE='match_deadline'; const WINDOW=10*60*60*1000; const PUBLIC_VAPID='BN7oJ4pAmj1KBgl43lfIGN_Gy7GBl14o8l1YuCt9V8Zg5qezvPjfydyW7WeMydUvpXoek76N9HmP_0Fx97BBGmw';
  const session=()=>typeof getSession==='function'?getSession():null, client=()=>window.supabaseClient;
  const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
  const countdown=d=>{const m=Math.max(0,Math.ceil((new Date(d)-Date.now())/60000)),h=Math.floor(m/60),r=m%60;return h?`H-${h}h${String(r).padStart(2,'0')}`:`H-${r} min`};
  const date=d=>new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(d));
  async function prefs(){const s=session();if(!s||!client())return{};const {data,error}=await client().rpc('get_notification_preferences',{p_pseudo:s.pseudo,p_code_hash:s.codeHash});if(error)console.error(error);return Object.fromEntries((data||[]).map(x=>[x.notification_type,x.enabled]));}
  async function pref(type,enabled){const s=session();if(!s||!client())return false;const {error}=await client().rpc('update_notification_preference',{p_pseudo:s.pseudo,p_code_hash:s.codeHash,p_notification_type:type,p_enabled:!!enabled});if(error){showToast?.('Impossible d’enregistrer la préférence.','error');return false}return true}
  async function missing(){const s=session();if(!s||!client())return[];const n=new Date(),l=new Date(n.getTime()+WINDOW);const [{data:m,error:a},{data:p,error:b}]=await Promise.all([client().from('matches').select('id,competition,phase,division,team1,team2,match_date').gt('match_date',n.toISOString()).lte('match_date',l.toISOString()).order('match_date'),client().from('pronostics').select('match_id').eq('pseudo',s.pseudo)]);if(a||b){console.error(a||b);return[]}const done=new Set((p||[]).map(x=>String(x.match_id)));return(m||[]).filter(x=>!done.has(String(x.id)))}
  async function saveSubscription(sub){const s=session();if(!s||!client())return false;const j=sub.toJSON();const {error}=await client().rpc('save_push_subscription',{p_pseudo:s.pseudo,p_code_hash:s.codeHash,p_endpoint:j.endpoint,p_subscription:j});if(error){console.error(error);showToast?.('Impossible d’enregistrer cet appareil.','error');return false}return true}
  function vapidBytes(){const base64=PUBLIC_VAPID.replace(/-/g,'+').replace(/_/g,'/');const padded=base64+'='.repeat((4-base64.length%4)%4);return Uint8Array.from(atob(padded),c=>c.charCodeAt(0))}
  async function enablePush(){if(!window.isSecureContext||!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window)){showToast?.('Les notifications push ne sont pas disponibles sur ce navigateur.','warning');return false}let permission=Notification.permission;if(permission==='default')permission=await Notification.requestPermission();if(permission!=='granted'){showToast?.('Autorisation des notifications refusée. Vérifiez les réglages du navigateur.','warning');return false}try{const reg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await reg.update();let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:vapidBytes()});if(!await saveSubscription(sub))return false;showToast?.('Notifications activées sur cet appareil !','success');return true}catch(error){console.error(error);showToast?.('Impossible d’activer les notifications push.','error');return false}}
  function matchModal(m){const rows=[...document.querySelectorAll('.match-row')];const r=rows.find(x=>(x.textContent||'').includes(m.team1)&&(x.textContent||'').includes(m.team2));if(r){r.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>r.click(),150)}else showToast?.('Ouvrez la compétition de ce match pour le pronostiquer.','info')}
  async function openCenter(){ensure();const ms=await missing();const modal=document.getElementById('notifications-center');modal.querySelector('.notifications-center-list').innerHTML=ms.length?ms.map(m=>`<button class="notification-match-item" data-id="${esc(m.id)}"><span><strong>${esc(m.team1)} × ${esc(m.team2)}</strong><small>${esc(date(m.match_date))}</small></span><b>${esc(countdown(m.match_date))}</b></button>`).join(''):'<div class="notifications-empty">🎉 Aucun match à pronostiquer dans les 10 prochaines heures.</div>';modal.style.display='flex';modal.querySelectorAll('.notification-match-item').forEach(b=>b.onclick=()=>{const m=ms.find(x=>String(x.id)===b.dataset.id);if(m){modal.style.display='none';matchModal(m)}})}
  function ensure(){if(document.getElementById('notifications-settings-modal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="notifications-settings-modal" class="modal-overlay notifications-modal"><div class="modal-box notifications-settings-box"><div class="modal-header"><h3>🔔 Gestion des notifications</h3><button class="modal-close" data-close>✕</button></div><div id="notifications-settings-body"></div></div></div><div id="notifications-center" class="modal-overlay notifications-modal"><div class="modal-box notifications-center-box"><div class="modal-header"><div><h3>🔔 Pronostics à compléter</h3><p>Tous les matchs dans les 10 prochaines heures sans pronostic.</p></div><button class="modal-close" data-close>✕</button></div><div class="notifications-center-list"></div></div></div>`);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal-overlay').style.display='none');document.querySelectorAll('.notifications-modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.style.display='none'})}
  async function settings(){ensure();const body=document.getElementById('notifications-settings-body'),p=await prefs(),state='Notification'in window?Notification.permission:'unsupported';body.innerHTML=`<div class="notification-browser-state"><span>${state==='granted'?'🟢':state==='denied'?'🔴':'⚪'}</span><div><strong>${state==='granted'?'Notifications autorisées':state==='denied'?'Notifications bloquées':'Notifications non activées'}</strong><small>${state==='granted'?'Cet appareil peut recevoir les alertes push.':'Cliquez sur Activer pour demander l’autorisation.'}</small></div></div><button id="enable-push-now" class="btn primary notifications-enable">Activer les notifications</button><div class="notification-setting-row"><div><strong>H-x pour pronostiquer</strong><small>Un match sans pronostic dans les 10 prochaines heures.</small></div><label class="notification-switch"><input id="notification-pref-match-deadline" type="checkbox" ${p[TYPE]!==false?'checked':''}><span></span></label></div>`;body.querySelector('#enable-push-now').onclick=enablePush;body.querySelector('#notification-pref-match-deadline').onchange=async e=>{const ok=await pref(TYPE,e.target.checked);if(ok&&e.target.checked)await enablePush()};document.getElementById('notifications-settings-modal').style.display='flex'}
  function button(){const hero=document.querySelector('#account-logged-in-view .account-hero');if(!hero||document.getElementById('notifications-account-button'))return;const b=document.createElement('button');b.id='notifications-account-button';b.className='btn ghost notifications-account-button';b.innerHTML='🔔 <span>Notifications</span>';b.onclick=settings;hero.appendChild(b)}
  function styles(){if(document.getElementById('notifications-styles'))return;const s=document.createElement('style');s.id='notifications-styles';s.textContent=`.notifications-account-button{display:inline-flex;gap:7px;margin:8px auto 0}.notifications-modal{z-index:1250}.notifications-settings-box,.notifications-center-box{width:min(600px,calc(100vw - 24px));max-height:88vh;overflow:hidden}.notifications-center-list{overflow:auto;max-height:calc(88vh - 100px)}.notifications-modal p{color:var(--text-muted);font-size:.72rem}.notification-browser-state,.notification-setting-row{display:flex;align-items:center;gap:12px;background:var(--bg-match);border:1px solid var(--border);border-radius:12px;padding:14px;margin-bottom:12px}.notification-browser-state>span{font-size:1.1rem}.notification-browser-state strong,.notification-browser-state small,.notification-setting-row strong,.notification-setting-row small{display:block}.notification-browser-state small,.notification-setting-row small{color:var(--text-muted);font-size:.68rem;margin-top:4px}.notification-setting-row{justify-content:space-between}.notifications-enable{width:100%;margin-bottom:12px}.notification-match-item{width:100%;display:flex;justify-content:space-between;align-items:center;gap:12px;text-align:left;background:var(--bg-match);color:var(--text-main);border:1px solid var(--border);border-radius:12px;padding:13px 14px;margin-bottom:8px;cursor:pointer}.notification-match-item span{display:flex;flex-direction:column;gap:4px}.notification-match-item small{color:var(--text-muted);font-size:.68rem}.notification-match-item b{background:var(--accent);color:#fff;border-radius:999px;padding:5px 9px;font-size:.68rem}.notifications-empty{text-align:center;padding:30px;color:var(--text-muted)}.notification-switch{position:relative;width:46px;height:26px;flex:0 0 46px}.notification-switch input{opacity:0;width:0;height:0}.notification-switch span{position:absolute;inset:0;background:#cbd5e1;border-radius:999px;cursor:pointer}.notification-switch span:before{content:'';position:absolute;width:20px;height:20px;left:3px;top:3px;background:#fff;border-radius:50%;transition:.2s}.notification-switch input:checked+span{background:var(--accent)}.notification-switch input:checked+span:before{transform:translateX(20px)}`;document.head.appendChild(s)}
  function init(){styles();button();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(console.error);if(new URLSearchParams(location.search).get('notifications')==='1')setTimeout(openCenter,700)}
  window.ProneNotifications={enablePush,openCenter};window.addEventListener('load',init);document.addEventListener('DOMContentLoaded',init);setInterval(button,1500);
})();
